// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInitialFile():Promise<main.FileInfo>;

export function OpenFileDialog():Promise<main.FileInfo>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<main.FileInfo>;
